config/routes.rb
Mifd::Application.routes.draw do
=begin
  namespace :api do
    namespace :v1 do
      resource :tweets
    end
  end
=end
  resources :categories

  namespace :api do
    namespace :v1 do
      resources :tweets do
        collection do
          get 'rank'
          get 'trend'
        end
      end
      resources :user_tweets, only: [:create] 
      resources :users do
        collection do
          post 'follow'
        end
      end
    end
  end

  delete '/api/v1/user_tweets/:tweet_uuid' => 'api/v1/user_tweets#destroy'
  resources :users do
    collection do
      post 'follow'
    end
  end
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'tweets/recent' => 'tweets#recent', as: 'recent_tweets'
  get 'tweets/people' => 'tweets#people', as: 'people_tweets'
  get 'tweets/test' => 'tweets#test'
  get 'categories/recent/:id' => 'categories#recent', as: 'recent_categories'
  get 'categories/people/:id' => 'categories#people', as: 'people_categories'
  root to: 'tweets#recent'
  resources :tweets

  

end

app/models/tweet.rb
class Tweet
  class << self
    def set_user_desc=(user_desc)
      @user_desc  = user_desc
    end
    def client=(client)
      @client = client
    end
  end
  include Mongoid::Document
  include AutoHtmlFor

  field :uuid, type: String
  field :text, type: String
  field :created_at, type: DateTime
  field :retweet_count, type: Integer
  field :favorite_count, type: Integer
  field :score, type: Integer

  scope :mifd_rank, order_by("score DESC")
  has_many :user_tweets, autosave: true
  belongs_to :category
  belongs_to :user
  scope :tweet_uuid, ->(tweet_uuid){where(tweet_uuid: tweet_uuid)}
  scope :today, where(:created_at.gte => Date.today-1)
=begin
  auto_html for :text do
    html_escape
    image
    youtube(:width => 400, :height => 250, :autoplay => true)
    link :target => '_blank', :rel => 'nofollow'
    simple_format
  end
=end

  def self.tweet_with_user(tweets)
    tweets.each_with_object([]){|tweet, tweet_with_user|
      tweet.attributes[:user] = tweet.user.attributes
      tweet[:user_tweets] = UserTweet.where(user_desc: @user_desc,tweet_id: tweet.id) 
      tweet[:is_retweet] = is_already_request(tweet, 'R')
      tweet[:is_favorite] = is_already_request(tweet, 'F')
      tweet_with_user <<  tweet.attributes
    }
  end

  def self.people
    tweets = Tweet.tweet_with_user(Tweet.includes(:user).today.asc(:name))
  end

  def self.recent
    tweets = Tweet.tweet_with_user(Tweet.includes(:user).today.desc(:created_at))
  end

  def self.rank
    tweets = Tweet.tweet_with_user(Tweet.includes(:user).mifd_rank.today)
  end

  def self.is_already_request(tweet, type)
    tweet[:user_tweets].to_a.map{|user_tweet| user_tweet[:type].eql? type}.include?(true)
  end

  def self.delete_tweet
   Tweet.where(:created_at.lt => Date.today ).delete 
  end

  def self.create_tweet
    APP_CONFIG['tweet_user'].each_with_index do |(category, tweet_users), idx|
      category = Category.find_or_create_by(name: category.to_s, id: idx+1)
      tweet_users.each do |tweet_user|
        begin
          p tweet_user
          Twitter.user_timeline(tweet_user, :count => 10).each do |timeline|
            if timeline.in_reply_to_status_id.nil?
              user = User.save(timeline)
              tweet = Tweet.new(
                  :created_at => timeline.created_at,
                  :text => timeline.text,
                  :retweet_count => timeline.retweet_count,
                  :favorite_count => timeline.favorite_count,
                  :score => timeline.retweet_count+timeline.favorite_count,
                  :uuid => timeline.id)
              if !Tweet.where(uuid: timeline.id).exists?
                tweet.save
                user.tweets.push(tweet)
                category.tweets.push(tweet)
              else
                Tweet.where(uuid: timeline.id).update(score: timeline.retweet_count+timeline.favorite_count)
              end
              user.save
            end#endof if
          end#endof do
        rescue Twitter::Error::TooManyRequests, Twitter::Error::Unauthorized => error
          if error == Twitter::Error::Unauthorized
            next
          elsif error == Twitter::Error::TooManyRequests
            sleep error.rate_limit.reset_in
            retry
          end
        end#end of begin
      end
    end
  end
end

app/controllers/api/v1/tweets_controller.rb
module Api
  module V1
    class TweetsController < ApplicationController
      respond_to :json
      Mongoid.logger.level = Logger::DEBUG
      def index
        @result = Kaminari.paginate_array(Tweet.rank).page(params[:page]).per(10)
        render :json => @result.to_json
      end
      def rank
        @result = Kaminari.paginate_array(Tweet.rank).page(params[:page]).per(10)
        render :json => @result.to_json
      end
      def trend
        trends = Twitter.trends(23424868)
        render :json => trends
      end
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :client

  def test
    @client = Twitter.status(params[:id])
  end

  def index
    gon.tweets = @tweets = Kaminari.paginate_array(Tweet.rank).page(params[:page]).per(10)
    gon.type = 1
  end

  def recent
    gon.tweets = @tweets = Kaminari.paginate_array(Tweet.recent).page(params[:page]).per(10)
    gon.type = 2
    respond_to do |format|
      format.html
      format.json {render json: @tweets.to_json }
    end
  end

  def people
    gon.tweets = @tweets = Kaminari.paginate_array(Tweet.people).page(params[:page]).per(10)
    gon.type = 3
  end

  def show
    begin
      hash = {:tweet => @tweet = @client.status(params[:id]),
              :user => current_user}
      respond_to do |format|
        format.html
        format.json {render json: hash.to_json }
      end
    rescue Mongoid::Errors::DocumentNotFound 
      render :status => 500, :text => 'Not Exists'
    end
  end

  private

  def client
    Tweet.client = @client
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def escape_http(text)
    text.gsub(/(https?:\/\/([-\w\.]+)+(:\d+)?(\/([\w\/_\.]*(\?\S+)?)?)?)/){|s|"<a target='_blank' href=#{s}>#{s}</a>"}.html_safe
  end
end

app/views/mobile/tweets/_category.html.erb
<ul data-role="listview" data-inset="true" data-theme="d" data-divider-theme="a" data-count-theme="b">
  <li data-role="list-divider">
    Category
  </li>
  <%@categories.each do |category| %>
    <li>
      <%= link_to category.name, recent_categories_path(category) %>
    </li>
<%end%>
</ul>

app/views/mobile/tweets/_category_order.html.erb
<ul data-role="listview" data-inset="true" data-theme="d" data-divider-theme="a" data-count-theme="b">
  <li data-role="list-divider">
    정렬방법
  </li>
  <li>
    <%= link_to "인기순", @category %>
  </li>
  <li>
    <%= link_to "최신순", recent_categories_path(@category) %>
  </li>
  <li>
    <%= link_to "인물순", people_categories_path(@category) %>
  </li>
</ul>

app/views/mobile/tweets/_index.html.erb
<ul id="tweets" data-role="listview" data-inset="true">
  <% tweets.each do |tweet|%>
    <li>
      <%=image_tag(tweet[:user][:image], alt: "Fail") %> 
      <strong><%=link_to tweet[:user][:name].truncate(12), "http://twitter.com/#{tweet[:user][:screen_name]}"%></strong>
      <span class="time"><%=time_ago_in_words(tweet[:created_at].localtime) %></span>
      <div class="text"><%=escape_http(tweet[:text])%></div>
      <%=hidden_field(:uuid,nil,:value => tweet[:uuid])%>
      <span class="more-show"><%=link_to "더 보기", tweet_path(tweet[:uuid])%></span>
    </li>
  <% end %>
</ul>
<%= paginate tweets %>

app/views/mobile/tweets/_order.html.erb
<ul data-role="listview" data-inset="true" data-theme="d" data-divider-theme="a" data-count-theme="b">
  <li data-role="list-divider">
    정렬방법
  </li>
  <li>
    <%= link_to "인기순", tweets_path %>
  </li>
  <li>
    <%= link_to "최신순", recent_tweets_path %>
  </li>
  <li>
    <%= link_to "인물순", people_tweets_path %>
  </li>
</ul>

app/views/mobile/tweets/recent.html.erb
<%=render :partial => "mobile/tweets/index", :locals => {:tweets => @tweets, :type => 'index'} %>

app/views/mobile/tweets/show.html.erb
<%=content_tag(:div, class: "main-tweet-container") do %>
  <%=content_tag(:table, id: "tweet-main") do %>
    <%=content_tag(:tbody) do %>
    <tr>
      <td class="avatar">
        <%=image_tag(@tweet.user.profile_image_url, alt: "프로필")%>
      </td>
      <td class="user-info">
        <div class="fullname">
          <a href="">
            <%=link_to "http://twitter.com/#{@tweet.user.screen_name}" do %>
              <strong><%=@tweet.user.name%></strong>
            <%end%>
          </a>
        </div>
        <a href="">
          <span class="username">
            <%=link_to "http://twitter.com/#{@tweet.user.screen_name}" do %>
              <span>@<%=@tweet.user.screen_name%></span>
            <%end%>
          </span>
        </a>
      </td>
      <td class="follow-button-container">
        <%if !@tweet.user.following %>
          <span class="w-button-common w-button-follow">
            <%=text_field_tag(nil,nil,{src: "https://ma.twimg.com/twitter-mobile/fc48126ff2f004e1c7d4d7405a7f6b01ccdfa537/images/sprites/followplus.gif", type: 'image', alt: '팔로우하기'})%>
          </span>
        <%end%>
      </td>
    </tr>
    <tr>
      <td class="tweet-content" colspan="3">
        <div class="tweet-text" data-id="">
          <%=escape_http(@tweet.text)%>
        </div>
      </td>
    </tr>
    <tr>
      <td class="optional-section" colspan="3">
        <%=content_tag(:table, class: "tweet-stat") do %>
          <tbody>
            <tr>
              <td class="stat">
                <span class="nb">
                  <span class="starnum"><%=@tweet.favorite_count%> Favorite</span>
                </span>
              </td>
              <td class="stat">
                <span class="nb">
                  <span class="starnum"><%=@tweet.retweet_count%> Retweet</span>
                </span>
              </td>
            </tr>
          </tbody>
        <%end%>
      </td>
    </tr>
    <tr class="last-section">
      <td class="optional-section" colspan="3">
        <%=content_tag(:table, class: "main-tweet-actions") do %>
          <tbody>
            <tr>
              <td class="action border-right">
                <a href="">
                  <%if !@tweet.retweeted%>
                    <span class="retweet">
                      <%= image_tag "jquery.mobile/1396851569_retweet.png" %>
                    </span>
                  <%else%>
                    <span class="retweeted">
                      <%= image_tag "jquery.mobile/1396851700_retweet.png" %>
                    </span>
                  <%end%>
                </a>
              </td>
              <td class="action">
                <a href="">
                  <%if !@tweet.favorited%>
                  <span class="favorite">
                    <%= image_tag "jquery.mobile/1396851445_89.png" %>
                  </span>
                  <%else%>
                    <span class="favorited">
                      <%= image_tag "jquery.mobile/1396851385_keditbookmarks.png" %>
                    </span>
                  <%end%>
                </a>
              </td>
            </tr>
          </tbody>
          <%end%>
      </td>
    </tr>
    <%end%>
  <%end%>
<%end%>